# Generated by Django 4.2.30 on 2026-07-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortcuts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("view_dashboard", "View Dashboard"),
                            ("view_shortcut", "View Shortcut"),
                            ("start_practice", "Start Practice"),
                            ("complete_practice", "Complete Practice"),
                            ("unlock_achievement", "Unlock Achievement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, default="")),
                (
                    "shortcut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shortcuts.shortcut",
                    ),
                ),
            ],
        ),
    ]
