# Generated by Django 3.1.8 on 2026-07-14 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField(default=0)),
                ('badge_key', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('application', 'Application-specific')], max_length=24)),
                ('app_focus', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('difficulty', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=1)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('unlock_after', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='trainer.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mouse_click', 'Mouse click'), ('keyboard_shortcut', 'Keyboard shortcut'), ('app_switch', 'Application switch'), ('clipboard_action', 'Clipboard action'), ('browser_action', 'Browser action'), ('idle', 'Idle'), ('workflow_repeat', 'Repeated workflow')], max_length=40)),
                ('app_name', models.CharField(blank=True, max_length=120)),
                ('event_key', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=1)),
                ('metadata', trainer.models.JSONTextField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('windows_combo', models.CharField(max_length=120)),
                ('mac_combo', models.CharField(blank=True, max_length=120)),
                ('key_signature', models.CharField(max_length=180)),
                ('purpose', models.TextField()),
                ('when_to_use', models.TextField()),
                ('example', models.TextField()),
                ('category', models.CharField(max_length=80)),
                ('difficulty', models.CharField(max_length=40)),
                ('apps', models.CharField(max_length=240)),
                ('estimated_seconds_saved', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to='trainer.lesson')),
            ],
            options={
                'ordering': ['lesson__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('reason', models.TextField()),
                ('estimated_seconds_saved_daily', models.PositiveIntegerField(default=0)),
                ('confidence', models.PositiveIntegerField(default=75)),
                ('source_signal', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortcut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.shortcut')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reaction_time_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wrong_attempts', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', trainer.models.JSONTextField(blank=True, default=list)),
                ('completed_shortcuts', trainer.models.JSONTextField(blank=True, default=list)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('estimated_time_saved_minutes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_shortcuts', models.PositiveIntegerField(default=0)),
                ('total_shortcuts', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_speed_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('weak_areas', trainer.models.JSONTextField(blank=True, default=list)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=120)),
                ('window_class', models.CharField(blank=True, max_length=160)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('switch_count', models.PositiveIntegerField(default=0)),
                ('observed_on', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'app_name', 'observed_on')},
            },
        ),
    ]
