# Generated by Django 4.2.30 on 2026-07-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon_svg",
                    models.TextField(
                        help_text="Inline SVG path code for premium graphic rendering"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keys_windows",
                    models.CharField(help_text="e.g., Ctrl+Shift+P", max_length=100),
                ),
                (
                    "keys_mac",
                    models.CharField(help_text="e.g., Cmd+Shift+P", max_length=100),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("editing", "Editing"),
                            ("window", "Window Management"),
                            ("terminal", "Terminal / CLI"),
                            ("system", "System Actions"),
                            ("formatting", "Formatting"),
                            ("search", "Search & Replace"),
                            ("other", "Miscellaneous"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_time_saved",
                    models.DecimalField(
                        decimal_places=1,
                        default=2.0,
                        help_text="Estimated seconds saved per execution",
                        max_digits=4,
                    ),
                ),
                (
                    "example",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contextual example of when to use it",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcuts",
                        to="shortcuts.application",
                    ),
                ),
            ],
        ),
    ]
