# Generated by Django 4.2.30 on 2026-07-13 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortcuts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(default=100.0, help_text="Accuracy percentage"),
                ),
                ("response_time", models.FloatField(help_text="Time taken in seconds")),
                ("is_correct", models.BooleanField(default=True)),
                ("xp_earned", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shortcut",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="shortcuts.shortcut",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
