LESSONS = [
    {
        "id": 1,
        "title": "Everyday Editing",
        "category": "Core productivity",
        "difficulty": "Beginner",
        "duration": 6,
        "shortcuts": [
            {
                "name": "Copy",
                "combo": ["Ctrl", "C"],
                "mac_combo": ["Cmd", "C"],
                "keys": ["control", "c"],
                "purpose": "Copy selected text or objects.",
                "when": "Use when moving details between documents, chat, tickets, or spreadsheets.",
                "example": "Copy a client note from email into your CRM without opening a menu.",
                "saved": 12,
                "apps": ["Windows", "Mac", "Word", "Excel", "Chrome"],
                "category": "Editing",
                "difficulty": "Beginner",
            },
            {
                "name": "Paste",
                "combo": ["Ctrl", "V"],
                "mac_combo": ["Cmd", "V"],
                "keys": ["control", "v"],
                "purpose": "Insert copied content.",
                "when": "Use after copying text, files, slides, rows, or design layers.",
                "example": "Paste a status update into Slack after copying it from Notion.",
                "saved": 12,
                "apps": ["Windows", "Mac", "Word", "Excel", "PowerPoint"],
                "category": "Editing",
                "difficulty": "Beginner",
            },
            {
                "name": "Cut",
                "combo": ["Ctrl", "X"],
                "mac_combo": ["Cmd", "X"],
                "keys": ["control", "x"],
                "purpose": "Move selected content instead of duplicating it.",
                "when": "Use when reorganizing paragraphs, spreadsheet cells, or file names.",
                "example": "Move a paragraph from the intro to the conclusion in one action.",
                "saved": 10,
                "apps": ["Windows", "Mac", "Word", "Excel"],
                "category": "Editing",
                "difficulty": "Beginner",
            },
            {
                "name": "Undo",
                "combo": ["Ctrl", "Z"],
                "mac_combo": ["Cmd", "Z"],
                "keys": ["control", "z"],
                "purpose": "Reverse the last action.",
                "when": "Use immediately after deleting, typing, formatting, or moving the wrong thing.",
                "example": "Restore a deleted spreadsheet formula before it breaks your model.",
                "saved": 18,
                "apps": ["Windows", "Mac", "Figma", "Photoshop", "VS Code"],
                "category": "Recovery",
                "difficulty": "Beginner",
            },
            {
                "name": "Redo",
                "combo": ["Ctrl", "Y"],
                "mac_combo": ["Cmd", "Shift", "Z"],
                "keys": ["control", "y"],
                "purpose": "Reapply an action after undoing it.",
                "when": "Use while comparing edits or restoring an accidental undo.",
                "example": "Bring back a slide layout after testing a different version.",
                "saved": 14,
                "apps": ["Windows", "Mac", "PowerPoint", "Photoshop"],
                "category": "Recovery",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 2,
        "title": "Find, Save, Select",
        "category": "Document control",
        "difficulty": "Beginner",
        "duration": 7,
        "shortcuts": [
            {
                "name": "Find",
                "combo": ["Ctrl", "F"],
                "mac_combo": ["Cmd", "F"],
                "keys": ["control", "f"],
                "purpose": "Search within the current page, file, or document.",
                "when": "Use when scanning policies, docs, logs, or long spreadsheets.",
                "example": "Find the exact invoice number in a 40-page PDF.",
                "saved": 35,
                "apps": ["Windows", "Mac", "Chrome", "Word", "VS Code"],
                "category": "Search",
                "difficulty": "Beginner",
            },
            {
                "name": "Replace",
                "combo": ["Ctrl", "H"],
                "mac_combo": ["Cmd", "Shift", "H"],
                "keys": ["control", "h"],
                "purpose": "Replace repeated text in one pass.",
                "when": "Use when updating names, labels, URLs, or recurring wording.",
                "example": "Replace an old product name across a proposal.",
                "saved": 45,
                "apps": ["Windows", "Mac", "Word", "Excel", "VS Code"],
                "category": "Search",
                "difficulty": "Intermediate",
            },
            {
                "name": "Select All",
                "combo": ["Ctrl", "A"],
                "mac_combo": ["Cmd", "A"],
                "keys": ["control", "a"],
                "purpose": "Select everything in the active field, page, or file.",
                "when": "Use before copying, deleting, formatting, or replacing a full body of content.",
                "example": "Select every cell in a sheet before applying a uniform format.",
                "saved": 20,
                "apps": ["Windows", "Mac", "Excel", "Word", "Chrome"],
                "category": "Editing",
                "difficulty": "Beginner",
            },
            {
                "name": "Save",
                "combo": ["Ctrl", "S"],
                "mac_combo": ["Cmd", "S"],
                "keys": ["control", "s"],
                "purpose": "Save the active file.",
                "when": "Use after meaningful changes, especially in desktop apps.",
                "example": "Save a client presentation before sharing your screen.",
                "saved": 16,
                "apps": ["Windows", "Mac", "Word", "Excel", "PowerPoint", "Photoshop"],
                "category": "File",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 3,
        "title": "Browser Command Center",
        "category": "Browser",
        "difficulty": "Intermediate",
        "duration": 8,
        "shortcuts": [
            {
                "name": "New Tab",
                "combo": ["Ctrl", "T"],
                "mac_combo": ["Cmd", "T"],
                "keys": ["control", "t"],
                "purpose": "Open a fresh browser tab.",
                "when": "Use when researching without losing your current page.",
                "example": "Open a tab for a competitor page during market research.",
                "saved": 20,
                "apps": ["Chrome", "Windows", "Mac"],
                "category": "Browser",
                "difficulty": "Beginner",
            },
            {
                "name": "Reopen Closed Tab",
                "combo": ["Ctrl", "Shift", "T"],
                "mac_combo": ["Cmd", "Shift", "T"],
                "keys": ["control", "shift", "t"],
                "purpose": "Bring back the tab you just closed.",
                "when": "Use after closing a reference, ticket, or dashboard too quickly.",
                "example": "Recover a pricing page after closing it during a call.",
                "saved": 40,
                "apps": ["Chrome", "Windows", "Mac"],
                "category": "Browser",
                "difficulty": "Intermediate",
            },
            {
                "name": "History",
                "combo": ["Ctrl", "H"],
                "mac_combo": ["Cmd", "Y"],
                "keys": ["control", "h"],
                "purpose": "Open browser history.",
                "when": "Use when you need a page from earlier in the day.",
                "example": "Find the documentation page you read before lunch.",
                "saved": 30,
                "apps": ["Chrome", "Windows", "Mac"],
                "category": "Browser",
                "difficulty": "Intermediate",
            },
            {
                "name": "Downloads",
                "combo": ["Ctrl", "J"],
                "mac_combo": ["Cmd", "Shift", "J"],
                "keys": ["control", "j"],
                "purpose": "Open the downloads list.",
                "when": "Use after downloading invoices, reports, CSV files, or assets.",
                "example": "Open the latest exported CSV without hunting through folders.",
                "saved": 25,
                "apps": ["Chrome", "Windows", "Mac"],
                "category": "Browser",
                "difficulty": "Intermediate",
            },
            {
                "name": "Bookmark Page",
                "combo": ["Ctrl", "D"],
                "mac_combo": ["Cmd", "D"],
                "keys": ["control", "d"],
                "purpose": "Save the current page as a bookmark.",
                "when": "Use for dashboards, documentation, reports, and recurring tools.",
                "example": "Bookmark a weekly analytics dashboard before closing it.",
                "saved": 22,
                "apps": ["Chrome", "Windows", "Mac"],
                "category": "Browser",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 4,
        "title": "Power User Flow",
        "category": "Advanced productivity",
        "difficulty": "Advanced",
        "duration": 10,
        "shortcuts": [
            {
                "name": "Multi Cursor",
                "combo": ["Ctrl", "Alt", "Down"],
                "mac_combo": ["Option", "Cmd", "Down"],
                "keys": ["control", "alt", "arrowdown"],
                "purpose": "Edit multiple lines at once.",
                "when": "Use when changing repeated labels, variables, rows, or list prefixes.",
                "example": "Add the same prefix to several lines in VS Code.",
                "saved": 60,
                "apps": ["VS Code"],
                "category": "Code",
                "difficulty": "Advanced",
            },
            {
                "name": "Command Palette",
                "combo": ["Ctrl", "Shift", "P"],
                "mac_combo": ["Cmd", "Shift", "P"],
                "keys": ["control", "shift", "p"],
                "purpose": "Open app commands without searching menus.",
                "when": "Use in VS Code, Figma, or productivity tools with command palettes.",
                "example": "Format a file or switch theme without touching menus.",
                "saved": 35,
                "apps": ["VS Code", "Figma"],
                "category": "Navigation",
                "difficulty": "Advanced",
            },
            {
                "name": "Open Recent File",
                "combo": ["Ctrl", "P"],
                "mac_combo": ["Cmd", "P"],
                "keys": ["control", "p"],
                "purpose": "Jump to a file by name.",
                "when": "Use in code editors and document-heavy tools.",
                "example": "Open a CSS file directly from the keyboard.",
                "saved": 42,
                "apps": ["VS Code", "Figma"],
                "category": "Navigation",
                "difficulty": "Intermediate",
            },
        ],
    },
    {
        "id": 5,
        "title": "Windows Navigation",
        "level": "Intermediate",
        "category": "Windows",
        "difficulty": "Intermediate",
        "duration": 8,
        "shortcuts": [
            {
                "name": "Switch Applications",
                "combo": ["Alt", "Tab"],
                "mac_combo": ["Cmd", "Tab"],
                "keys": ["alt", "tab"],
                "task": "Switch to the next open application.",
                "purpose": "Move between open applications without reaching for the taskbar.",
                "when": "Use when comparing information across chat, browser, documents, and spreadsheets.",
                "example": "Jump from a browser report back to Excel during analysis.",
                "saved": 18,
                "apps": ["Windows"],
                "category": "Navigation",
                "difficulty": "Intermediate",
            },
            {
                "name": "Lock Screen",
                "combo": ["Win", "L"],
                "mac_combo": ["Control", "Cmd", "Q"],
                "keys": ["meta", "l"],
                "task": "Lock your computer.",
                "purpose": "Secure your workstation instantly.",
                "when": "Use when stepping away from your desk.",
                "example": "Lock before joining a meeting in another room.",
                "saved": 10,
                "apps": ["Windows"],
                "category": "Security",
                "difficulty": "Beginner",
            },
            {
                "name": "Open File Explorer",
                "combo": ["Win", "E"],
                "mac_combo": ["Cmd", "Space"],
                "keys": ["meta", "e"],
                "task": "Open the file browser.",
                "purpose": "Open files and folders without hunting for the icon.",
                "when": "Use when downloading, attaching, or organizing files.",
                "example": "Open your downloads folder while preparing a report.",
                "saved": 16,
                "apps": ["Windows"],
                "category": "File",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 6,
        "title": "Chrome Deep Work",
        "level": "Application-specific",
        "category": "Chrome",
        "difficulty": "Intermediate",
        "duration": 9,
        "shortcuts": [
            {
                "name": "Close Current Tab",
                "combo": ["Ctrl", "W"],
                "mac_combo": ["Cmd", "W"],
                "keys": ["control", "w"],
                "task": "Close the current tab.",
                "purpose": "Close a browser tab without moving to the tab strip.",
                "when": "Use when clearing finished research, dashboards, or duplicate pages.",
                "example": "Close an old ticket tab after updating the customer.",
                "saved": 18,
                "apps": ["Chrome"],
                "category": "Browser",
                "difficulty": "Beginner",
            },
            {
                "name": "Paste Without Formatting",
                "combo": ["Ctrl", "Shift", "V"],
                "mac_combo": ["Cmd", "Shift", "V"],
                "keys": ["control", "shift", "v"],
                "task": "Paste text without formatting.",
                "purpose": "Paste clean text into editors, docs, chat, and forms.",
                "when": "Use when copied text carries unwanted fonts, colors, or spacing.",
                "example": "Paste a quote into a proposal without breaking the format.",
                "saved": 32,
                "apps": ["Chrome", "Word", "PowerPoint"],
                "category": "Editing",
                "difficulty": "Intermediate",
            },
            {
                "name": "Focus Address Bar",
                "combo": ["Ctrl", "L"],
                "mac_combo": ["Cmd", "L"],
                "keys": ["control", "l"],
                "task": "Focus the browser address bar.",
                "purpose": "Search or type a URL immediately.",
                "when": "Use when opening a site, searching, or replacing the current address.",
                "example": "Jump from a dashboard to a documentation search.",
                "saved": 22,
                "apps": ["Chrome"],
                "category": "Browser",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 7,
        "title": "Office Essentials",
        "level": "Application-specific",
        "category": "Office",
        "difficulty": "Intermediate",
        "duration": 10,
        "shortcuts": [
            {
                "name": "Bold Text",
                "combo": ["Ctrl", "B"],
                "mac_combo": ["Cmd", "B"],
                "keys": ["control", "b"],
                "task": "Make selected text bold.",
                "purpose": "Emphasize headings, labels, and important statements.",
                "when": "Use while formatting Word documents, slides, and emails.",
                "example": "Bold the next action in meeting notes.",
                "saved": 12,
                "apps": ["Word", "PowerPoint"],
                "category": "Formatting",
                "difficulty": "Beginner",
            },
            {
                "name": "Insert Excel Table",
                "combo": ["Ctrl", "T"],
                "mac_combo": ["Cmd", "T"],
                "keys": ["control", "t"],
                "task": "Create a table from selected spreadsheet data.",
                "purpose": "Turn spreadsheet ranges into filterable tables.",
                "when": "Use when cleaning reports, lists, and exports.",
                "example": "Convert a CSV export into a sortable Excel table.",
                "saved": 45,
                "apps": ["Excel"],
                "category": "Spreadsheet",
                "difficulty": "Intermediate",
            },
            {
                "name": "Start Slide Show",
                "combo": ["F5"],
                "mac_combo": ["Cmd", "Shift", "Return"],
                "keys": ["f5"],
                "task": "Start the presentation from the beginning.",
                "purpose": "Launch a deck without searching PowerPoint controls.",
                "when": "Use before presenting or testing a deck.",
                "example": "Start a client presentation during a screen share.",
                "saved": 20,
                "apps": ["PowerPoint"],
                "category": "Presentation",
                "difficulty": "Beginner",
            },
        ],
    },
    {
        "id": 8,
        "title": "VS Code Acceleration",
        "level": "Application-specific",
        "category": "VS Code",
        "difficulty": "Advanced",
        "duration": 11,
        "shortcuts": [
            {
                "name": "Toggle Terminal",
                "combo": ["Ctrl", "`"],
                "mac_combo": ["Control", "`"],
                "keys": ["control", "`"],
                "task": "Open or hide the integrated terminal.",
                "purpose": "Move between code and terminal without changing windows.",
                "when": "Use while running tests, servers, and scripts.",
                "example": "Open the terminal to run a Django check after editing a view.",
                "saved": 28,
                "apps": ["VS Code"],
                "category": "Code",
                "difficulty": "Intermediate",
            },
            {
                "name": "Go to Definition",
                "combo": ["F12"],
                "mac_combo": ["F12"],
                "keys": ["f12"],
                "task": "Jump to a symbol definition.",
                "purpose": "Navigate code without file hunting.",
                "when": "Use when tracing functions, models, components, or variables.",
                "example": "Jump from a view call to the model it uses.",
                "saved": 35,
                "apps": ["VS Code"],
                "category": "Code",
                "difficulty": "Advanced",
            },
        ],
    },
]


def all_shortcuts():
    shortcuts = []
    for lesson in LESSONS:
        for shortcut in lesson["shortcuts"]:
            item = shortcut.copy()
            item["lesson_id"] = lesson["id"]
            item["lesson_title"] = lesson["title"]
            item["lesson_level"] = lesson.get("level", lesson["difficulty"])
            item["task"] = item.get("task", item["purpose"])
            shortcuts.append(item)
    return shortcuts


MOCK_USAGE_SUMMARY = {
    "productivity_score": 74,
    "potential_time_saved_minutes": 31,
    "focus_time_minutes": 146,
    "idle_minutes": 28,
    "app_switches": 96,
    "mouse_clicks": 1240,
    "keyboard_shortcuts": 188,
    "clipboard_actions": 148,
    "browser_tabs_opened": 42,
    "browser_tabs_closed": 31,
    "manual_saves": 52,
    "repeated_workflows": 7,
    "most_used_apps": [
        {"name": "Chrome", "minutes": 164, "switches": 38, "score": 71},
        {"name": "Excel", "minutes": 92, "switches": 17, "score": 68},
        {"name": "VS Code", "minutes": 76, "switches": 13, "score": 82},
        {"name": "Word", "minutes": 44, "switches": 8, "score": 77},
    ],
    "time_wasters": [
        {"label": "Browser tab churn", "detail": "42 new tabs and 31 tab closes today.", "minutes": 9},
        {"label": "Repeated copy and paste", "detail": "148 clipboard actions across Chrome, Word, and Excel.", "minutes": 8},
        {"label": "Frequent app switching", "detail": "96 switches between core work apps.", "minutes": 7},
        {"label": "Manual save loop", "detail": "52 save-related actions in document tools.", "minutes": 4},
    ],
    "strengths": [
        "Editing shortcuts are becoming automatic.",
        "VS Code navigation has the highest accuracy this week.",
        "You recover from mistakes quickly with Undo and Redo.",
    ],
    "weak_areas": [
        "Browser recovery shortcuts",
        "Clean paste workflows",
        "Windows app switching",
    ],
    "recent_activity": [
        "Desktop agent summarized 1,240 mouse clicks without collecting content.",
        "Detected repeated paste formatting cleanup in Word.",
        "Observed high Chrome tab churn during research work.",
        "Completed Browser Command Center practice with 84% accuracy.",
    ],
}

MOCK_USAGE_EVENTS = [
    {"event_type": "app_switch", "event_key": "app_switch", "count": MOCK_USAGE_SUMMARY["app_switches"], "app_name": "Windows"},
    {"event_type": "clipboard_action", "event_key": "copy", "count": MOCK_USAGE_SUMMARY["clipboard_actions"], "app_name": "Chrome"},
    {"event_type": "browser_action", "event_key": "new_tab", "count": MOCK_USAGE_SUMMARY["browser_tabs_opened"], "app_name": "Chrome"},
    {"event_type": "browser_action", "event_key": "close_tab", "count": MOCK_USAGE_SUMMARY["browser_tabs_closed"], "app_name": "Chrome"},
    {"event_type": "workflow_repeat", "event_key": "manual_save", "count": MOCK_USAGE_SUMMARY["manual_saves"], "app_name": "Office"},
]

SIGNAL_RECOMMENDATIONS = [
    {
        "signal": "42 browser tabs opened",
        "shortcut": "New Tab",
        "combo": "Ctrl+T",
        "reason": "You opened 42 browser tabs. Learn Ctrl+T to make that action instant.",
        "daily_saved": 6,
        "confidence": 91,
    },
    {
        "signal": "31 browser tabs closed",
        "shortcut": "Reopen Closed Tab",
        "combo": "Ctrl+Shift+T",
        "reason": "You closed tabs 31 times. Learn Ctrl+Shift+T to recover a tab without history search.",
        "daily_saved": 7,
        "confidence": 88,
    },
    {
        "signal": "148 clipboard actions",
        "shortcut": "Paste Without Formatting",
        "combo": "Ctrl+Shift+V",
        "reason": "You copied or pasted text 148 times. Learn Ctrl+Shift+V for clean paste workflows.",
        "daily_saved": 8,
        "confidence": 86,
    },
    {
        "signal": "96 application switches",
        "shortcut": "Switch Applications",
        "combo": "Alt+Tab",
        "reason": "You switched apps 96 times. Learn Alt+Tab to reduce pointer travel.",
        "daily_saved": 7,
        "confidence": 84,
    },
    {
        "signal": "52 manual saves",
        "shortcut": "Save",
        "combo": "Ctrl+S",
        "reason": "You manually saved 52 times. Learn Ctrl+S to keep the save habit fast.",
        "daily_saved": 4,
        "confidence": 79,
    },
    {
        "signal": "User edits documents",
        "shortcut": "Undo and Redo",
        "combo": "Ctrl+Z / Ctrl+Y",
        "reason": "Document editing sessions had repeated correction patterns.",
        "daily_saved": 5,
        "confidence": 82,
    },
]

STATS = {
    "total_shortcuts": len(all_shortcuts()),
    "total_lessons": len(LESSONS),
    "completed_shortcuts": 17,
    "weekly_minutes": [12, 18, 9, 24, 16, 28, 14],
    "xp": 3540,
    "level": 8,
    "streak": 9,
    "time_saved_minutes": 68,
    "accuracy": 89,
    "course_progress": 46,
    "today_progress": 62,
    "productivity_score": MOCK_USAGE_SUMMARY["productivity_score"],
    "potential_time_saved_minutes": MOCK_USAGE_SUMMARY["potential_time_saved_minutes"],
}

ACHIEVEMENTS = [
    ("First Shortcut", "Complete your first correct shortcut.", True),
    ("7 Day Streak", "Practice for seven days in a row.", True),
    ("30 Day Streak", "Build a month-long keyboard habit.", False),
    ("Productivity Master", "Complete every beginner and intermediate lesson.", False),
    ("Keyboard Ninja", "Hit 95% accuracy in an advanced lesson.", False),
    ("Speed Learner", "Finish a lesson in under five minutes.", True),
]
